apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "actions-runner-controller.managerPodSecurityPolicyName" . }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
spec:
  allowedCapabilities: [] # drop default capabilities
  allowPrivilegeEscalation: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 2000
        max: 2000
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 2000
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
