kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "actions-runner-controller.managerPodSecurityPolicyName" . }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
   - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ include "actions-runner-controller.managerPodSecurityPolicyName" . }}
