kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "actions-runner-controller.managerNetworkPolicy" . }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "actions-runner-controller.selectorLabels" . | nindent 6 }}
  # allow all egress traffic
  egress:
  - {}
  ingress:
  - ports:
    - port: 8080  # metrics
    - port: 9443  # webhook server
    - port: 8443  # rbac proxy
  policyTypes:
  - Ingress
  - Egress
