{{- if .Values.crds.install }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "actions-runner-controller.crdInstallName" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "actions-runner-controller.crdInstallAnnotations" . | nindent 4 }}
  labels:
    role: {{ include "actions-runner-controller.crdInstallName" . | quote }}
spec:
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.crds.securityContext.runAsGroup }}
        max: {{ .Values.crds.securityContext.runAsGroup }}
  hostPID: false
  hostIPC: false
  hostNetwork: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: {{ .Values.crds.securityContext.runAsGroup }}
        max: {{ .Values.crds.securityContext.runAsGroup }}
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: {{ .Values.crds.securityContext.runAsUser }}
        max: {{ .Values.crds.securityContext.runAsUser }}
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'configMap'
{{- end }}
