{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
{{- if .Values.crds.install }}
  {{- range $path, $_ := .Files.Glob "files/**" }}
    {{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actions-runner-controller.crdInstallName" . }}-{{ $path | base | replace "_" "-" | replace "." "-" | trimSuffix ".yaml" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "actions-runner-controller.crdInstallAnnotations" . | nindent 4 }}
  labels:
    role: {{ include "actions-runner-controller.crdInstallLabel" . | quote }}
data:
  content: |
{{ .Files.Get $path | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
